import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
OUTPUT_DIR = "data"

DEFAULT_TRI_AREA = 0.05
GAUSS_TRI_ORDER = 5
GAUSS_LINE_ORDER = 5
BOUNDARY_DENSITY_PTS = 100

LOSS_TYPE    = "mse"
DEFAULT_LR   = 1e-2
TRAIN_EPOCHS = 2000      
BC_PENALTY   = 10.0    

NTK_ANALYSIS_EVERY  = 200  
NTK_ANALYSIS_POINTS = 256
NTK_NODE_ORDER = "xy" 

FEM_TRI_AREA     = 0.005
FEM_REFINE_LEVELS = [0.1, 0.05, 0.01, 0.005]