import torch

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
OUTPUT_DIR = "data"

TRAIN_TRI_AREA = 0.1
TRAIN_BOUNDARY_DENSITY = 20
TRAIN_GAUSS_TRI_ORDER = 5
TRAIN_GAUSS_LINE_ORDER = 1

EVAL_TRI_AREA = 0.0125
EVAL_BOUNDARY_DENSITY = 200
EVAL_GAUSS_TRI_ORDER = 5
EVAL_GAUSS_LINE_ORDER = 4

ADAM_LR = 2e-4
ADAM_EPOCHS = 1000

LBFGS_EPOCHS = 500
LBFGS_LR = 1.0
LBFGS_MAX_ITER = 20
LBFGS_TOLERANCE_GRAD = 1e-7
LBFGS_TOLERANCE_CHANGE = 1e-9

BC_PENALTY = 10.0

AUTO_BALANCE_ENABLED = True